name: Deploy API to WebServer

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Select Docker image tag'
        required: true

env:
  IMAGE_NAME: cabonline-ts-api
  REGISTRY: 10.200.11.15:5000

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Run the Docker image
      run: >
        docker run 
        -dt
        -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" 
        -e "ASPNETCORE_ENVIRONMENT=Development" 
        -e "ASPNETCORE_URLS=http://+:80" 
        -e "DOTNET_USE_POLLING_FILE_WATCHER=1" 
        -e "NUGET_PACKAGES=/root/.nuget/fallbackpackages" 
        -e "NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages" 
        -p 32985:80 
        --name TSApi-${{ github.event.inputs.docker_tag }}
        ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.docker_tag }}
